<Base>:
    MDFloatLayout:
        md_bg_color: [1,1,1,1]
    MDLabel:
        id: id_angka
        text: root.label_text
        halign: "center"

    MDFloatingActionButton:
        icon: "plus"
        elevation: 0
        pos_hint: {'center_x': 0.5,'center_y': 0.4}
        on_release:
            root.tambah()
    MDFloatingActionButton:
        icon: "minus"
        elevation: 0
        pos_hint: {'center_x': 0.5,'center_y': 0.3}
        on_release:
            root.kurang()
